name: Setup
description: Checkout code, set up docker, optionally login to GHCR
inputs:
  needs-docker-login:
    description: 'Whether to login to GitHub Package Registry (GHCR) or not'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Package Registry
      if: ${{ inputs.needs-docker-login == 'true' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}
