name: Setup
description: Checkout code, set up docker, unit test, loin to ghcr, build and push docker image
inputs:
  endpoint:
    description: The endpoint
    required: true
  token:
    description: GitHub token for package registry
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Unit test
      run: make test-$ENDPOINT
      shell: bash
      env:
        ENDPOINT: ${{ inputs.endpoint }}

    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push Docker image
      run: make push-$ENDPOINT
      shell: bash
      env:
        ENDPOINT: ${{ inputs.endpoint }}
        DOCKER_REGISTRY: ghcr.io/${{ github.repository }}
