spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/resume?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
    username: kang
    password: 3bQv7XyT
job:
  profile:
    auth:
      register-router: /password-setting
    site:
      scheme: http
      domain: www.job-profile.com
