spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobprofile?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""

logging:
  level:
    com.kang.jobprofile: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
