name: Backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/**'
      - 'Makefile'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ci
        uses: ./.github/actions/ci
        with:
          endpoint: backend
          token: ${{ secrets.PACKAGES_TOKEN }}
