# This workflow is triggered on push events to the main branch
# for changes in the backend directory or the workflow file itself.
name: Backend CI
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yaml'
      - 'Makefile'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up For Test
        uses: ./.github/workflows/setup.yaml@main
        uses: ./.github/workflows/setup.yaml@${{ github.sha }}
      - name: Test backend
        run: make test-backend

  build-image-and-push:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up For Build
        uses: ./.github/workflows/setup.yaml@main
        uses: ./.github/workflows/setup.yaml@${{ github.sha }}
        with:
          needs-docker-login: true
      - name: Push backend
        run: make push-backend
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}
