# This workflow is triggered on push events to the main branch
# for changes in the backend directory or the workflow file itself.
name: Backend CI
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yaml'
      - 'Makefile'
jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test backend
        run: make test-backend
  build-image-and-push:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Push backend
        run: make push-backend
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}
