name: Backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  ci-backend:
    name: CI Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ci
        name: Test and Build
        uses: ./.github/actions/ci
        with:
          endpoint: backend
          token: ${{ secrets.PACKAGES_TOKEN }}
