name: Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  ci-frontend:
    name: CI Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ci
        name: Test and Build
        uses: ./.github/actions/ci
        with:
          endpoint: frontend
          token: ${{ secrets.PACKAGES_TOKEN }}
